- action:
  - alias: Office_Fan_On
    data:
      entity_id: script.office_fan_on
    service: script.turn_on
  alias: Office Fan On
  id: '1496540509506'
  trigger:
  - entity_id: switch.office_fan
    from: 'off'
    platform: state
    to: 'on'
- action:
  - alias: office_fan_off
    data:
      entity_id: script.office_fan_off
    service: script.turn_on
  alias: Office Fan Off
  id: '1496541544214'
  trigger:
  - entity_id: switch.office_fan
    from: 'on'
    platform: state
    to: 'off'
- action:
  - alias: bedroom_Fan_On
    data:
      entity_id: script.bedroom_fan_on
    service: script.turn_on
  alias: Bedroom Fan On
  id: '1496547509506'
  trigger:
  - entity_id: switch.bedroom_fan
    from: 'off'
    platform: state
    to: 'on'
- action:
  - alias: bedroom_fan_off
    data:
      entity_id: script.bedroom_fan_off
    service: script.turn_on
  alias: Bedroom Fan Off
  id: '1496549544214'
  trigger:
  - entity_id: switch.bedroom_fan
    from: 'on'
    platform: state
    to: 'off'
- action:
  - data:
      message: The front door was just unlocked.
    service: notify.pushbullet_lh
  alias: Lexi_FrontDoorUnlocked_Pushbullet
  id: '1498358968358'
  trigger:
  - entity_id: lock.front_door_locked_4_0
    from: locked
    platform: state
    to: unlocked
- action:
  - data:
      message: The front door was just locked.
    service: notify.pushbullet_lh
  alias: Lexi_FrontDoorLocked_Pushbullet
  id: '1798358968358'
  trigger:
  - entity_id: lock.front_door_locked_4_0
    from: unlocked
    platform: state
    to: locked

    
#Door code stuff
- action:
  - alias: Rachael door code enable
    data:
      entity_id: script.set_rachael_door_code
    service: script.turn_on
  alias: Rachael Code Enable
  id: '14965475654366'
  trigger:
  - entity_id: switch.rachael_code_enabled
    from: 'off'
    platform: state
    to: 'on'
- action:
  - alias: Rachael door code disable
    data:
      entity_id: script.empty_rachael_code
    service: script.turn_on
  alias: Rachael Code Disable
  id: '14965475654393'
  trigger:
  - entity_id: switch.rachael_code_enabled
    from: 'on'
    platform: state
    to: 'off'
#kat
- action:
  - alias: kat door code enable
    data:
      entity_id: script.set_kat_door_code
    service: script.turn_on
  alias: kat Code Enable
  id: '14965475654366'
  trigger:
  - entity_id: switch.kat_code_enabled
    from: 'off'
    platform: state
    to: 'on'
- action:
  - alias: kat door code disable
    data:
      entity_id: script.empty_kat_code
    service: script.turn_on
  alias: kat Code Disable
  id: '14965475654393'
  trigger:
  - entity_id: switch.kat_code_enabled
    from: 'on'
    platform: state
    to: 'off'
    
#Steph
- action:
  - alias: steph door code enable
    data:
      entity_id: script.set_steph_door_code
    service: script.turn_on
  alias: steph Code Enable
  id: '14965475654366'
  trigger:
  - entity_id: switch.steph_code_enabled
    from: 'off'
    platform: state
    to: 'on'
- action:
  - alias: steph door code disable
    data:
      entity_id: script.empty_steph_code
    service: script.turn_on
  alias: steph Code Disable
  id: '14965475654393'
  trigger:
  - entity_id: switch.steph_code_enabled
    from: 'on'
    platform: state
    to: 'off'

#ruth
- action:
  - alias: ruth door code enable
    data:
      entity_id: script.set_ruth_door_code
    service: script.turn_on
  alias: ruth Code Enable
  id: '14965475654366'
  trigger:
  - entity_id: switch.ruth_code_enabled
    from: 'off'
    platform: state
    to: 'on'
- action:
  - alias: ruth door code disable
    data:
      entity_id: script.empty_ruth_code
    service: script.turn_on
  alias: ruth Code Disable
  id: '14965475654393'
  trigger:
  - entity_id: switch.ruth_code_enabled
    from: 'on'
    platform: state
    to: 'off'
    