- alias: 'office_fan_on'
  trigger:
    platform: state
    entity_id: switch.office_fan
    state: 'on'
  action:
    service: script.turn_on
    entity_id: script.office_fan_on
  
- alias: 'office_fan_off'
  trigger:
    platform: state
    entity_id: switch.office_fan
    state: 'off'
  action:
    service: script.turn_on
    entity_id: script.office_fan_off

- alias: 'bedroom_fan_on'
  trigger:
    platform: state
    entity_id: switch.bedroom_fan
    state: 'on'
  action:
    service: script.turn_on
    entity_id: script.bedroom_fan_on
  
- alias: 'bedroom_fan_off'
  trigger:
    platform: state
    entity_id: switch.bedroom_fan
    state: 'off'
  action:
    service: script.turn_on
    entity_id: script.bedroom_fan_off