
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 194
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize: !include customize.yaml  

# Enables the frontend
frontend: !include frontend.yaml

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  server_port: 8123
  ssl_certificate: /etc/letsencrypt/live/hejman.duckdns.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/hejman.duckdns.org/privkey.pem
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
  base_url: https://hejman.duckdns.org

# Checks for available updates
updater:

#write the logs a bit more verbose.
logger:
  default: warning
 # logs:
 #   homeassistant.components.climate: debug
 #   homeassistant.components.nest: debug

#Notifiers
notify:
  - name: Pushbullet_nh
    platform: pushbullet
    api_key: !secret pushbullet_api_nh
    
  - name: Pushbullet_lh
    platform: pushbullet
    api_key: !secret pushbullet_api_lh
  
  - name: slack
    platform: slack
    api_key: !secret slack_key
    default_channel: '#ha-alerts'    

#Nest
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
#  sensors:
#    monitored_conditions:
#      - 'temperature'
#      - 'target'
climate:
  platform: nest

# Discover some devices automatically
#discovery:

#Z-Wave installation 6/24/2017
zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_key

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

#Hue
light:
  platform: hue
  host: 10.0.0.25
  
  

#MQTT for device tracker
#mqtt:
#  broker: 10.0.0.20
#  port: 1883
#  client_id: home-assistant-1
#  username: !secret mqtt_user
#  password: !secret mqtt_password

#device_tracker:
#  platform: owntracks

emulated_hue:
  listen_port: 80
  host_ip: 10.0.0.20
  expose_by_default: false
  type: alexa
  exposed_domains:
      #- group
    - switch
    #- scene
    - lock


media_player:
  - platform: cast    
#amcrest:
#  - host: 10.0.0.45
#    username: !secret amcrest_user
#    password: !secret amcrest_pw
    #resolution: low
#    stream_source: mjpeg
#    name: front door camera
#    sensors:
#      - motion_detector
    
#camera:
#  - platform: amcrest  

###Includes###      
script: !include script.yaml
switch: !include switches.yaml
automation: !include automations.yaml
group: !include groups.yaml
#scene: !include scenes.yaml
shell_command: !include shell.yaml
#sensor: !include_dir_list sensors/
sensor: !include sensors.yaml
####TEST####
panel_custom: 
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml